Solucionada funcionalidad filtrado de actores.
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #101
Opened 2020-01-17 16:19 UTC by victorbrobles

Hemos arreglado el fallo de la funcionalidad del filtrado de actores y hemos adaptado el código al nuevo formato. La documentación de la funcionalidad está en la API REST de la wiki

2020-01-17 16:35 UTC, DanielRiveraPaniagua requested changes
Bien, no veo fallos en la implementación. 

Podríais mejorarlo haciendo que en vez de ser necesario distinguir entre fecha _x o intervalo_fecha_x simplemente si en fecha_x detecta - hace lo trata como un intervalo (como cuando en películas trabajamos con el año)

No creo que esté bien la parte del selectAll con id porque no queremos que el id sea una forma de filtrarlo en esa funcionalidad. Y si podéis devolver el selectByName en las DAOImpl que es útil para otras cosas (no lo quiteis del selectAll donde es necesario, simplemente dejadlo también)

2020-01-17 17:15 UTC, victorbrobles commented
Vale, dejamos el selectByID dentro de selectAll entonces? Porque aunque no sea muy útil funciona bien, y es otra posibilidad de filtrado, pero si queréis lo sacamos fuera y lo dejamos como estaba.

2020-01-17 17:53 UTC, DanielRiveraPaniagua commented
> Vale, dejamos el selectByID dentro de selectAll entonces? Porque aunque no sea muy útil funciona bien, y es otra posibilidad de filtrado, pero si queréis lo sacamos fuera y lo dejamos como estaba.

Yo lo sacaría más que nada porque selectAll es más un filtrado de cara al cliente, además de que ya tenemos un selectByID a parte como método distinguido, y no encuentro la utilidad de que un cliente filtre en selectAll por id. Pero es una preferencia personal al fin y al cabo, sois vosotros los que estáis implementando esta parte y como no rompe con la estructura de lo propuesto en ningún caso, no es un si o no fijo. Por mi dejadlo como prefiráis.

2020-01-17 18:58 UTC, victorbrobles commented
Vale, lo demás ya está solucionado

2020-01-18 00:22 UTC, dpoloa commented on src/main/java/urjc/isi/dao/implementaciones/ActoresDAOImpl.java
> +import urjc.isi.entidades.Peliculas;
Creo que esto no es necesario en esta implementación DAO

2020-01-18 00:24 UTC, dpoloa approved these changes

2020-01-18 08:46 UTC, merged