Añadida funcionalidad película por género
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #71
Opened 2019-12-29 12:48 UTC by dcabezas96

Toda la documentación está puesta en la wiki

2019-12-29 13:37 UTC, DanielRiveraPaniagua requested changes
Bastante en desacuerdo con muchas cosas: 
* selectAllgeneros debería ir en generoscontroller y selectpeliculasgénero debería ir en peliculas implementado en selectall (como el ejemplo de las películas en las que ha trabajado un actor). Ésto viene explicado en la documentación que subimos con la funcionalidad básica.
* Habéis comentado todo el connect del generic, cuando funcionaba perfectamente , debéis dejarlo para que funcione con postgresql (ya lo he comentado en varias ocasiones). 
* En peliculasDAO implícitación al crear la tabla cambiáis lo del rating a text, mal, por que el rating es un decimal (la razón a que debáis cambiarlo pasa porque estáis trabajando con jdbc como no deberíais). 
* En la query de selectallbygénero en películas, reducidla (select * ...)
* PeliculasGenerosDAOImpl es una relación, extiende de RelacionesDAOImpl no de GenericDAO.
* Si GenericDAO necesita la interfaz películas, habéis incluido algo mal, porque es genérica.
* RelacionesDAO no necesita la entidad relaciones ni el list para funcionar.

2019-12-29 17:49 UTC, ismagt commented
- SelectAllgeneros,muesta el resultado de todos las relaciones (id_pelicula, genero), no puedo ponerlo en generos controller, ya que ahi hace referencia solo a los generos.
- Lo hize por que pensaba que a lo mejor algún compañero lo pudiera probar, si lo comento no funciona, pero ya esta solucionado.
- Estoy en proceso, por alguna razon si pongo decimal, y subo el fichero txt, da error de tipos.
- si la reduzco así la querie, tendría que cambiar las entidades etc, además yo lo que quiero es sacar las peliculas, no sacar la información de peliculas + género (al poner select *) es lo que estoy haciendo. Se entiende que si filtro por género el user no desea la información de tipo de género.

2019-12-29 18:43 UTC, DanielRiveraPaniagua commented
Si reduces la query no pasaría nada por qué como en peliculasdaoimpl aunque también devuelve un resultado mucho mayor, luego extraemos lo que nos interesa.

2019-12-30 12:40 UTC, DanielRiveraPaniagua requested changes
GenericDAO no necesita entidades.peliculas.
GenericDAOImpl, ordenad la clausala try catch (opinión propia)
RelacionesDAOImp habéis dejado comentado el connect
RelacionesDAO no necesita ni util.List ni entidades y tenéis ésta ultima repetida y comentada.
Añadís ficheros de pruebas entre ellos el pruebapeliculas al menos sobra, el chiste es muy malo a pesar de ser yo quien lo puso.
También tenéis conflictos, no se cuales, antes de mergear tened cuidado con ésto.

@ismagt puesto que searchbygenero usa el genero service, concorde a lo que estuvimos hablando ayer, no tengo una opinión fija de si colocarlo en peliculascontroller o generoscontroller. Por un lado es un post que va a devolver una url que finalmente genera una lista de películas, por otro lado usa una funcionalidad propia del género. Es una buena cuestión que os dejo resolver a vosotros como consideréis. Se me ocurre probar una cosa, que /peliculas/searchbyGenero dirija a un generocontroller en vez de a un peliculas controller donde esté esta funcionalidad. 

> get("/searchByGenero", GeneroController::searchByGenero);  // o algo del estilo

2020-01-02 17:25 UTC, jaime0907 requested changes
Hay un pequeño fallo en el Peliculas.java.

2020-01-02 17:25 UTC, jaime0907 commented on src/main/java/urjc/isi/entidades/Peliculas.java
> +	    this.setDuracion(calificacion);
Aquí debería ser setCalificacion en vez de setDuracion. La implementación no falla porque de momento solo usamos el otro constructor, pero hay que cambiarlo

2020-01-03 10:45 UTC, dcabezas96 commented on src/main/java/urjc/isi/entidades/Peliculas.java
> +	    this.setDuracion(calificacion);
Ya está solucionado muchas gracias @jaime0907

2020-01-04 02:32 UTC, jaime0907 approved these changes

2020-01-07 18:35 UTC, closed without merging