Devel
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #73
Opened 2019-12-30 21:08 UTC by angeisa97

Hemos añadido los ficheros relativos a guionistas y directores, siguiendo la misma estructura que actores para posibles funcionalidades.

2019-12-30 22:09 UTC, DanielRiveraPaniagua requested changes
La build os falla, cosas que he detectado:
* GuionistasService, primera linea debería poner package.
* PeliculasDirectoresController, linea 54 una f al final.
* GuionistasDAOImpl, falta por cerrar la clase.

Resubidlo con éstos cambios a ver si la build deja de fallar.

2019-12-31 10:26 UTC, angeisa97 commented
Dejamos funcionando la build.

2019-12-31 14:07 UTC, DanielRiveraPaniagua approved these changes
Todo parece correcto

2020-01-03 10:07 UTC, oscarescuderoarnanz approved these changes

2020-01-03 10:09 UTC, merged