Añadida mejora en la funcionalidad de filtrado de genero y arrelgado bug #74
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #76
Opened 2020-01-03 10:23 UTC by ismagt

He añadido a la funcionalidad del filtrado de genero, que se pueda añadir más de un género consiguiendo, que filtre más de uno. Para ello es necesario mantener la tecla CTRL + (seleccionar  otro género) .

2020-01-03 12:14 UTC, DanielRiveraPaniagua commented
Qué diferencia este pull request del anterior? Se necesitan ambos? Solo éste?

2020-01-07 18:37 UTC, dcabezas96 commented
@DanielRiveraPaniagua habría que dejar nada más este pull request el número 76, que es la versión actualizada del 71, por tanto el 71 se puede borrar.

2020-01-07 18:51 UTC, oscarescuderoarnanz requested changes
Debeis arreglar los conflictos, por el contrario al margen de vuestra funcionalidad no se podrá aceptar.

2020-01-15 11:32 UTC, agallegoroz commented
Nos gustaría saber cuando estarán solucionados los conflictos ya que algunos ficheros son necesarios para una parte de nuestra funcionalidad y queda poco tiempo para la entrega. Si no se arreglasen con un cierto margen de tiempo para que sea posible probar nuestra funcionalidad y resolver pequeños problemas de última hora que surgiesen nos veremos obligados a implementar estos ficheros

2020-01-15 16:30 UTC, ismagt commented
> Nos gustaría saber cuando estarán solucionados los conflictos ya que algunos ficheros son necesarios para una parte de nuestra funcionalidad y queda poco tiempo para la entrega. Si no se arreglasen con un cierto margen de tiempo para que sea posible probar nuestra funcionalidad y resolver pequeños problemas de última hora que surgiesen nos veremos obligados a implementar estos ficheros

2020-01-15 16:30 UTC, closed without merging

2020-01-15 16:32 UTC, ismagt commented
> Nos gustaría saber cuando estarán solucionados los conflictos ya que algunos ficheros son necesarios para una parte de nuestra funcionalidad y queda poco tiempo para la entrega. Si no se arreglasen con un cierto margen de tiempo para que sea posible probar nuestra funcionalidad y resolver pequeños problemas de última hora que surgiesen nos veremos obligados a implementar estos ficheros

¿Qué funcionalidad estáis implementando para que existan ficheros que dependan de este pull request? He estado mirando el workflow, y no se que grupo sois, pero en principio no he visto ningún grupo que tenga que depender de nosotros, espero no equivocarme. Disculpa las molestias, intentaremos arreglarlo lo antes posible.