Filtrado por año nacimiento/muerte de actores, directores y guionistas.
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #77
Opened 2020-01-05 03:41 UTC by victorbrobles

Hemos añadido el filtrado por año de nacimiento, por año de muerte y por intervalo de años tanto de actores, directores como de guionistas.

Si os parecen bien los cambios modificamos la wiki para ver cómo queda la API REST con estas funcionalidades.

2020-01-05 08:50 UTC, DanielRiveraPaniagua requested changes
Todas las carpetas target/* no tienen que estar en el pull request.

Con los que se encuentren en un intervalo os referís a los que han nacido entre un intervalo de años, creo que el nombre no es del todo claro.

¿Habéis probado las querys? Porque tenéis fNacimiento y fMuerte cuando en la tabla es todo en minúsculas. Por otra parte, no son números esas dos, sino que son  de tipo text, ¿os va a dejar filtrarlo con </>?

2020-01-05 13:39 UTC, victorbrobles commented
Arreglados esos fallos. 
Probamos distintas querys y funcionaban con los símbolos <> y variables tipo text.

2020-01-05 17:25 UTC, DanielRiveraPaniagua requested changes
Revisando otra vez el pull request me he dado cuenta de un fallo que existía en el código de ActoresDAOImpl y que ha sido heredado tanto por vuestras querys como por directores y guionistas. Si lo podéis arreglar para todos estaría bien.

En ActoresDAOImpl cuando, en deleteByID, se forma la query "SELECT * from personas where fullnombre = " ese **personas** debería ser **actores**, en este caso.  SelectByName, y vuestras tres querys también heredan este error. Al mismo tiempo pasa lo mismo en DirectoresDAOImp y GuionistasDAOImpl pero con la tabla específica de cada uno.

Gracias por adelantado.

Añadís tablas_sql/.DS_Strore, creo que no es correcto.
 
Lo demás parece correcto.

Lo único que añadís en GuionistasService y DirectoresService importais urjc.isi.dao.implementaciones.ActoresDAOImpl que no debería ser necesario.

2020-01-05 18:01 UTC, DanielRiveraPaniagua approved these changes
Todo me parece correcto

2020-01-05 18:28 UTC, dpoloa commented on src/main/java/urjc/isi/dao/implementaciones/ActoresDAOImpl.java
> +		 String sql = "SELECT * from actores WHERE fmuerte < 2020";
Supongo que este no dará problemas si el campo de fmuerte está vacío. ¿Se podría hacer que esto funcionara si el campo fmuerte no es numérico? Es un detalle para hacer que no dependa de un número y que funcione en cualquier momento :)

2020-01-05 18:29 UTC, dpoloa approved these changes

2020-01-05 19:13 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/implementaciones/ActoresDAOImpl.java
> +		 String sql = "SELECT * from actores WHERE fmuerte < 2020";
fmuerte es de tipo texto, con un \N en caso de que esté vació, no he visto que de problemas ya que hace directamente la transformación de texto a números y no cuenta los \N en el proceso.

Aun así estoy intentando ver el como dejar el campo vacío de verdad en postgresql con algo como NaN y que funcione en java también. Pero en principio ésto sí funcionaría. (Ellos mismos lo contestan un poco más arriba)

> ¿Se podría hacer que esto funcionara si el campo fmuerte no es numérico?

No entiendo a que te refieres. 

Un cambio interesante justo en ese punto, sería poder elegir también esa fecha por si te interesan los muertos antes de x año. Pero entiendo que el grupo 4 intenta ver solamente los actores muertos hasta este año.

2020-01-05 23:17 UTC, victorbrobles commented on src/main/java/urjc/isi/dao/implementaciones/ActoresDAOImpl.java
> +		 String sql = "SELECT * from actores WHERE fmuerte < 2020";
Sí, en principio la idea era poner fmuerte = \N, pero. si pones eso en java da error, por eso puse <2020. De todas formas se puede modificar para pedirle al cliente un año y mirar los actores muertos antes de ese año

2020-01-07 13:57 UTC, oscarescuderoarnanz approved these changes

2020-01-07 14:42 UTC, merged