Funcionalidad Filtrado Tiempo
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #79
Opened 2020-01-07 13:49 UTC by oscarescuderoarnanz

Funcionalidad filtrado peliculas dado tiempo. 
Información del path a usar en la wiki.

2020-01-07 14:33 UTC, DanielRiveraPaniagua reviewed
Mañana miro mejor un par de cosas. En principio no lo veo mal aunque colocaría las cosas de manera diferente. Haría varios service dependiendo de si es mayor, menor o por rangos y, por tanto, varios métodos en DAOImpl.

¿Lo de string mayor y string menor no se puede comparar directamente con un equals en la clausula del if? (Para no tener demasiadas líneas de por medio)

2020-01-07 14:43 UTC, Noozh approved these changes
No veo nada raro

2020-01-08 14:59 UTC, DanielRiveraPaniagua requested changes

2020-01-08 14:59 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +			}
Toda esta parte debería estar en todo caso en un service, en vez en el controller.

2020-01-08 14:59 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/implementaciones/PeliculasDAOImpl.java
> +	  }else {
Creo que se podría ordenar mejor ya que es "select * from peliculas where  duracion" + simbolo + "=" + t1 + "Order by duracion asc"

2020-01-08 14:59 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/implementaciones/PeliculasDAOImpl.java
> +		  sql = "SELECT * from peliculas " + "where duracion>=" + t1 + " and duracion<=" + t2 + "ORDER BY duracion ASC";
Con éste casi haría un método distinto pero voy a comentar un poco más adelante un detalle que me he dado cuenta de todos los filtrados de selectAll

2020-01-08 15:07 UTC, DanielRiveraPaniagua commented
Vuestro pull request me ha mostrado un problema que tenemos con el código de selectAll actualmente. Issue #81

2020-01-15 16:44 UTC, dpoloa requested changes
Antes de ayer si veía vuestra funcionalidad correctamente, pero ahora solo veo cuatro archivos de los cuales tres están relacionados con los datos de la base de datos. ¿Ha ocurrido algo?

2020-01-15 16:44 UTC, dpoloa commented on DatosLimpios/filmsSelecc/guionistas.txt
> +nm0027271	Paul W.S. Anderson	1965	\N
Me parece que hay guionistas repetidos. Este es uno de los casos (Paul W.S. Anderson).

2020-01-15 16:50 UTC, DanielRiveraPaniagua commented on DatosLimpios/filmsSelecc/guionistas.txt
> +nm0027271	Paul W.S. Anderson	1965	\N
issue #74 . Están trabajando en la funcionalidad y en el arreglo de los datos

2020-01-15 17:00 UTC, felipecordente commented on DatosLimpios/filmsSelecc/guionistas.txt
> +nm0027271	Paul W.S. Anderson	1965	\N
Buenas @dpoloa, estas en lo cierto, la funcionalidad estaba funcionando, pero no con el formato finalmente acordado, asi que para mañana ya la tendremos con el formato correcto.
En cuanto a el fichero guionistas.txt, también estará corregido para mañana.

2020-01-15 17:09 UTC, oscarescuderoarnanz commented on DatosLimpios/filmsSelecc/guionistas.txt
> +nm0027271	Paul W.S. Anderson	1965	\N
@dpoloa estoy revisando tambien el resto de ficheros .txt por si algun otro fichero tuviera algun problema. Mañana estará todo subido, funcionalidad y ficheros *.txt.

2020-01-15 18:33 UTC, dpoloa commented on DatosLimpios/filmsSelecc/guionistas.txt
> +nm0027271	Paul W.S. Anderson	1965	\N
Perfecto, gracias por revisarlo todo.

2020-01-16 23:06 UTC, oscarescuderoarnanz commented
@dpoloa @DanielRiveraPaniagua Ya están revisados todos los datos, he detectado pequeños errores en directores y guionistas, los cuales ya están arreglados, revisarlos para ver si esta todo okey.
Además hemos añadido la funcionalidad de filtrado de tiempo la cual se encuntra ya acabada.

2020-01-17 08:09 UTC, DanielRiveraPaniagua requested changes
Arreglad estas 3 cosillas y creo que listo

2020-01-17 08:09 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		//return request.queryParams("duracion") + "<br/>" + filter.get("duracion").indexOf("<") + "<br/>" + result;
borradla

2020-01-17 08:09 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/proyectofinal/Main.java
> +       String result = new String("prueba 1");
Dejadlo como éstaba

2020-01-17 08:09 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/service/PeliculasService.java
> -			result = pelisDAO.selectAll();
Dejadlo como estaba

2020-01-17 09:36 UTC, DanielRiveraPaniagua approved these changes
Perfecto

2020-01-17 10:52 UTC, merged