Funcionalidad filtrado por géneros grupo 6
DanielRiveraPaniagua/ProyectoFinal_ISI pull request #95
Opened 2020-01-16 16:29 UTC by ismagt

Referente a los conflictos pull #76

2020-01-16 16:56 UTC, DanielRiveraPaniagua requested changes
Me gustaría ver una url con la app funcionando para ver como es. En principio éstas cosillas. Puesto que podéis filtrar por varios géneros, eso sí podría ser bueno estudiar como incluirlo en un selectAll para poder utilizarlo también.

Podéis así simplificar muchísimo la búsqueda por genéros en la query, where genero=terror or/and genero=x and genero=y ... (como lo tenéis más o menos), esto metido en un bucle dentro del selectall nos posibilita facilitar vuestro buscar a través de varios géneros. 

Si no me explico preguntadme por privado.

2020-01-16 16:56 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		gs = new GenerosService();
Esto debería irse al método concreto en el que se usa, en vez de estar aquí

2020-01-16 16:56 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/implementaciones/PeliculasDAOImpl.java
>  }
Esto es lo que os comenté, si lo unís como parte de selectAll mejor así también podemos aplicar un pequeño filtrado por género allí

2020-01-16 16:56 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/interfaces/GenericDAO.java
> +import urjc.isi.entidades.Peliculas;
No debería estar aquí

2020-01-16 16:56 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/dao/interfaces/RelacionesDAO.java
> +/*import urjc.isi.entidades.Relaciones;*/
Innecesario

2020-01-16 16:56 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		}
El controller no puede trabajar las querys, para eso usamos las clases dao, para aislar en ellas las bases de datos

2020-01-16 17:03 UTC, ismagt commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		gs = new GenerosService();
arreglado commit 73431b020ba525ecaaf4973563029db460a047c9

2020-01-16 17:09 UTC, dcabezas96 commented on src/main/java/urjc/isi/dao/interfaces/RelacionesDAO.java
> +/*import urjc.isi.entidades.Relaciones;*/
Arreglado en el commit número f8bfce532b74822b7605f2d3d61c4cbc96de3284

2020-01-16 17:10 UTC, dcabezas96 commented on src/main/java/urjc/isi/dao/interfaces/GenericDAO.java
> +import urjc.isi.entidades.Peliculas;
Arreglado en el commit número 9f9c2abedd0aaf60ddfa00b3a1ec8d3a346fe489

2020-01-16 17:59 UTC, ismagt commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		gs = new GenerosService();
no sobra ya que se llama a searchByGenero, aprox linea 195 :
List<Generos> output = gs.getAllGeneros();

2020-01-16 18:14 UTC, ismagt commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		gs = new GenerosService();
vale ya esta, finalmente lo he introducido en generos Controller

2020-01-16 18:15 UTC, ismagt commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		}
solucionado, ya esta en peliculasDaoImpl

2020-01-17 11:16 UTC, DanielRiveraPaniagua approved these changes
Se tiene que aprobar a pesar de estar a medio hacer algunas partes de la funcionalidad para poder seguir progresando con géneros. Todo lo que involucra esas tablas se encuentra bien acabado.

2020-01-17 11:16 UTC, DanielRiveraPaniagua commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		System.out.println("muestra");
Quita esta muestra XD

2020-01-17 11:21 UTC, merged

2020-01-17 11:26 UTC, dcabezas96 commented on src/main/java/urjc/isi/controladores/PeliculasController.java
> +		System.out.println("muestra");
arreglado en el commit 96c69ce2032b80ab4b338f3165f7480fe6dec4ec